# Generated by Django 5.2.6 on 2025-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Perfil')),
                ('system_prompt_template', models.TextField(help_text='Instrução detalhada para a IA. Use {data_atual} para a data de hoje.', verbose_name='System Prompt Template')),
                ('pydantic_schema_name', models.CharField(help_text='Nome da classe do schema em extraction.schemas (Ex: ProcessoJuridicoSchema).', max_length=100, verbose_name='Nome do Schema Pydantic')),
            ],
            options={
                'verbose_name': 'Perfil de Extração (Prompt)',
                'verbose_name_plural': 'Perfis de Extração (Prompts)',
            },
        ),
    ]
