# Generated by Django 5.2.6 on 2025-09-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('TRELLO', 'Trello Card Creation'), ('TELEGRAM', 'Telegram Notification')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha na Integração'), ('PENDING', 'Pendente de Execução'), ('RETRIED', 'Tentativa de Retry')], default='PENDING', max_length=20)),
                ('request_data', models.JSONField(blank=True, help_text='Payload enviado ao serviço externo.', null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Resposta recebida do serviço externo.', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(help_text='Email que acionou esta integração.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='emails.emailmessage')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integração',
                'indexes': [models.Index(fields=['email_message', 'service', 'status'], name='integration_email_m_9e4b33_idx')],
            },
        ),
    ]
