# Generated by Django 5.2.6 on 2025-11-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_mailbox_extraction_profile'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Configuração')),
                ('trello_api_key', models.CharField(blank=True, max_length=255, verbose_name='Trello API Key')),
                ('trello_api_token', models.CharField(blank=True, max_length=255, verbose_name='Trello API Token')),
                ('trello_list_id', models.CharField(blank=True, max_length=255, verbose_name='Trello List ID Padrão')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram Chat ID Padrão')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de Integração Externa',
                'verbose_name_plural': 'Configurações de Integração Externa',
            },
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='email_message',
            field=models.ForeignKey(help_text='Email que acionou esta integração.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs_ext', to='emails.emailmessage'),
        ),
    ]
