# Generated by Django 5.2.6 on 2025-11-18 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationconfig_alter_integrationlog_email_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
            preserve_default=False,
        ),
    ]
