# Generated by Django 5.2.6 on 2025-09-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Caixa')),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Busca')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caixa de Email',
                'verbose_name_plural': 'Caixas de Email',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID único do email (para idempotência)', max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('sender', models.EmailField(max_length=254)),
                ('received_at', models.DateTimeField(verbose_name='Recebido em (Timestamp IMAP)')),
                ('body_text', models.TextField(verbose_name='Corpo do Email (Texto Limpo)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Processamento'), ('PROCESSING', 'Em Processamento'), ('EXTRACTED', 'Dados Extraídos com Sucesso'), ('REVIEW', 'Requer Revisão Humana (IA Falhou)'), ('INTEGRATED', 'Integrado (Trello/Telegram OK)'), ('FAILED', 'Falha Crítica')], default='PENDING', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, help_text='Dados chave extraídos pela IA (JSON validado)', null=True)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='emails.mailbox')),
            ],
            options={
                'verbose_name': 'Mensagem de Email',
                'verbose_name_plural': 'Mensagens de Email',
                'indexes': [models.Index(fields=['status', 'received_at'], name='emails_emai_status_c5f0b2_idx')],
            },
        ),
    ]
