# Generated by Django 5.2.6 on 2025-11-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='extraction_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='extraction.extractionprofile', verbose_name='Perfil de Extração de IA'),
        ),
    ]
