# Generated by Django 5.2.6 on 2025-11-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_mailbox_extraction_profile'),
        ('integrations', '0002_integrationconfig_alter_integrationlog_email_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='integration_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='integrations.integrationconfig', verbose_name='Configuração de Integração Externa'),
        ),
    ]
