# Generated by Django 5.2.6 on 2025-11-18 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_mailbox_user'),
        ('extraction', '0002_extractionprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Regra')),
                ('priority', models.IntegerField(default=10, help_text='Prioridade de execução. Menor número é executado primeiro.')),
                ('is_active', models.BooleanField(default=True)),
                ('subject_contains', models.CharField(blank=True, help_text='Texto que o Assunto DEVE conter (deixe vazio para ignorar).', max_length=255, null=True)),
                ('sender_contains', models.CharField(blank=True, help_text='Texto que o Remetente DEVE conter (deixe vazio para ignorar).', max_length=255, null=True)),
                ('action_config', models.JSONField(blank=True, default=dict, help_text='Configurações para ações pós-extração (ex: Trello, Telegram).')),
                ('extraction_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extraction.extractionprofile', verbose_name='Perfil de Extração (IA) a ser usado')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='emails.mailbox', verbose_name='Caixa de E-mail Alvo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'ordering': ['priority', 'name'],
                'unique_together': {('mailbox', 'name')},
            },
        ),
    ]
