# Generated by Django 5.2.6 on 2025-11-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0002_mailbox_extraction_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Configuração')),
                ('trello_api_key', models.CharField(blank=True, max_length=255, verbose_name='Trello API Key')),
                ('trello_api_token', models.CharField(blank=True, max_length=255, verbose_name='Trello API Token')),
                ('trello_list_id', models.CharField(blank=True, max_length=255, verbose_name='Trello List ID Padrão')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram Bot Token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram Chat ID Padrão')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de Integração Externa',
                'verbose_name_plural': 'Configurações de Integração Externa',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('TRELLO', 'Trello Card Creation'), ('TELEGRAM', 'Telegram Notification')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha na Integração'), ('PENDING', 'Pendente de Execução'), ('RETRIED', 'Tentativa de Retry')], default='PENDING', max_length=20)),
                ('request_data', models.JSONField(blank=True, help_text='Payload enviado ao serviço externo.', null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Resposta recebida do serviço externo.', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(help_text='Email que acionou esta integração.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='emails.emailmessage')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integração',
                'indexes': [models.Index(fields=['email_message', 'service', 'status'], name='tasks_integ_email_m_fb98f5_idx')],
            },
        ),
    ]
